#!/usr/bin/env sh

APP="ptr"
AUTO_VERSION="git-revision+branch-unless-master"

BUILD_HOST="sandbox"
BUILD_USER="deployer"
BUILD_AT="/tmp/edeliver/$APP/builds"

STAGING_HOSTS="sandbox"
STAGING_USER="deployer"

PRODUCTION_HOSTS="vintock.com"
PRODUCTION_USER="deployer"

DELIVER_TO="/var/www/$APP"

# For *Phoenix* projects, symlink prod.secret.exs to our tmp source
pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/$BUILD_USER/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
    "
  fi
}
