#!/usr/bin/env sh

APP="ptr"
AUTO_VERSION="git-revision+branch-unless-master"

BUILD_HOST="sandbox"
BUILD_USER="deployer"
BUILD_AT="/tmp/edeliver/$APP/builds"

STAGING_HOSTS="sandbox"
STAGING_USER="deployer"

PRODUCTION_HOSTS="vintock.com"
PRODUCTION_USER="deployer"

DELIVER_TO="/var/www"

# For *Phoenix* projects, symlink prod.secret.exs to our tmp source
pre_erlang_get_and_update_deps() {
  local _prod_secret_path="/home/$BUILD_USER/prod.secret.exs"
  if [ "$TARGET_MIX_ENV" = "prod" ]; then
    __sync_remote "
      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
    "
  fi
}

pre_erlang_clean_compile() {
  status "Preparing assets with: yarn run build and phx.digest"
  __sync_remote "
    set -e

    cd '$BUILD_AT/assets'
    yarn install
    MIX_ENV='$TARGET_MIX_ENV' yarn run build

    cd '$BUILD_AT'
    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phx.digest $SILENCE
  "
}

# "Taken" from https://github.com/edeliver/edeliver/wiki/Symlink-static-for-nginx-or-apache
post_erlang_update() {
  symlink_static
}

post_upgrade_release() {
  symlink_static
}

symlink_static(){
  status "Running post update symlink"
  __remote "
    ln -sfn $DELIVER_TO/$APP/lib/$APP$RELEASE-$VERSION/priv/static $DELIVER_TO/$APP/static
  "
}
